language: go
go:
  - "1.14.x"

os:
  - linux

before_install:
  - sudo apt-get update && sudo apt-get -y install gcc-arm-linux-gnueabihf
  - nvm install 12
  - nvm use 12
  - npm install -g yarn

script:
  - ./build.sh

